import "./globals.css";
import type { Metadata } from "next";
import "tailwindcss/tailwind.css";
import { NavbarMobile } from "./globals/NavbarMobile";
import { Header } from "./globals/Header";
import { BurgerMenuProvider } from "./_providers/BurgermenuContext";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<BurgerMenuProvider>
				<body>
					<Header />
					<main>{children}</main>
					<footer></footer>
				</body>
			</BurgerMenuProvider>
		</html>
	);
}
