import './globals.css';
import type { Metadata } from 'next';
import 'tailwindcss/tailwind.css';
import { NavbarMobile } from './globals/NavbarMobile';
import { Header } from './globals/Header';
import { BurgerMenuProvider } from './_providers/BurgermenuContext';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<BurgerMenuProvider>
				<body>
					<Header />
					<main className='flex min-h-screen flex-col items-center'>
						{children}
					</main>
					<footer></footer>
				</body>
			</BurgerMenuProvider>
		</html>
	);
}
